baseurl = "https://blog.uyorum.net"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
languageCode = "ja-jp"
title = "@uyorumの雑記帳"
copyright = "uyorum All Right Reserved."
theme = "my-theme"
paginate = 9
disqusShortname = "uyorum"
googleAnalytics = "UA-43857839-1"

[indexes]
  category = "categories"
  tag = "tags"

[markup.goldmark.renderer]
  unsafe = true

[Params]
  logo = "https://avatars2.githubusercontent.com/u/2661975"
  description = "uyorum's tech blog"
  author = "uyorum"
  twitter = "uyorum"
  github = "uyorum"
  email = "uyorum.pub@gmail.com"

[permalinks]
  post = "/post/:filename/"
