baseurl = "https://blog.uyorum.net"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
languageCode = "ja-jp"
title = "@uyorumの雑記帳"
copyright = "uyorum All Right Reserved."
theme = "my-theme"
paginate = 9
disqusShortname = "uyorum"
pygmentsUseClasses = true

[indexes]
  category = "categories"
  tag = "tags"

[Params]
  logo = "https://avatars2.githubusercontent.com/u/2661975"
  description = "uyorum's tech blog"
  author = "uyorum"
  twitter = "uyorum"
  github = "uyorum"
  email = "uyorum.pub@gmail.com"
  amazonAssociate = "uyorum-22"
  googleSearchConsole = "1i1Op7whJ5gykPQAa7tjPVqL2kpAQQ2KsY6ZUFIU8p0"
  googleTagManager = "GTM-K2G6PBB"

[permalinks]
  post = "/post/:filename/"
